// Package fingerprint provides content-based static asset fingerprinting.
//
// It walks a source directory, hashes each file's contents (SHA-256, first 12
// hex chars), and writes fingerprinted copies (name.HASH.ext) to a separate
// output directory. A generated Go source file maps original paths to
// fingerprinted paths at compile time.
package fingerprint

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"io"
	"io/fs"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

// hashLen is the number of hex characters used from the SHA-256 digest.
const hashLen = 12

// fingerprintPattern matches filenames that contain a fingerprint hash.
var fingerprintPattern = regexp.MustCompile(`\.[0-9a-f]{12}\.`)

// skipFiles are filenames to skip during fingerprinting.
var skipFiles = map[string]bool{
	".gitkeep": true,
}

// sentinel is written to the dist directory so we can verify ownership
// before wiping it on subsequent runs.
const sentinel = ".hamr-fingerprint"

// Manifest maps original relative paths to their fingerprinted counterparts.
type Manifest struct {
	Files map[string]string
}

// WriteGoManifest writes a Go source file declaring a StaticManifest variable
// with the manifest entries baked in as a map literal.
func (m *Manifest) WriteGoManifest(path, pkg string) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("create manifest dir: %w", err)
	}

	var b strings.Builder
	b.WriteString("// Code generated by hamr gen static; DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "package %s\n", pkg)

	if len(m.Files) == 0 {
		b.WriteString("\n// StaticManifest maps original asset paths to fingerprinted paths.\n")
		b.WriteString("// Populated by hamr gen static.\n")
		b.WriteString("var StaticManifest map[string]string\n")
	} else {
		b.WriteString("\n// StaticManifest maps original asset paths to fingerprinted paths.\n")
		b.WriteString("var StaticManifest = map[string]string{\n")

		// Sort keys for deterministic output.
		keys := make([]string, 0, len(m.Files))
		for k := range m.Files {
			keys = append(keys, k)
		}
		sort.Strings(keys)

		for _, k := range keys {
			fmt.Fprintf(&b, "\t%q: %q,\n", k, m.Files[k])
		}
		b.WriteString("}\n")
	}

	return os.WriteFile(path, []byte(b.String()), 0o644)
}

// Fingerprint walks srcDir, hashes each file, and writes fingerprinted copies
// to distDir (mirroring the directory structure). The distDir is wiped first
// to remove stale files from previous runs.
func Fingerprint(srcDir, distDir string) (*Manifest, error) {
	if err := validateDistDir(distDir, srcDir); err != nil {
		return nil, err
	}

	// Wipe dist to remove stale fingerprinted files.
	if err := os.RemoveAll(distDir); err != nil {
		return nil, fmt.Errorf("clean %s: %w", distDir, err)
	}

	m := &Manifest{Files: make(map[string]string)}

	err := filepath.WalkDir(srcDir, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			return nil
		}

		name := d.Name()

		// Skip special files.
		if skipFiles[name] {
			return nil
		}

		rel, err := filepath.Rel(srcDir, path)
		if err != nil {
			return err
		}

		hash, err := hashFile(path)
		if err != nil {
			return fmt.Errorf("hash %s: %w", rel, err)
		}

		fpName := fingerprintedName(name, hash)
		fpPath := filepath.Join(distDir, filepath.Dir(rel), fpName)

		if err := copyFile(path, fpPath); err != nil {
			return fmt.Errorf("copy %s: %w", rel, err)
		}

		fpRel := filepath.Join(filepath.Dir(rel), fpName)
		// Normalise to forward slashes for the manifest.
		m.Files[filepath.ToSlash(rel)] = filepath.ToSlash(fpRel)

		return nil
	})
	if err != nil {
		return nil, fmt.Errorf("walk %s: %w", srcDir, err)
	}

	// Write sentinel so future runs can verify ownership.
	if err := os.WriteFile(filepath.Join(distDir, sentinel), nil, 0o644); err != nil {
		return nil, fmt.Errorf("write sentinel: %w", err)
	}

	return m, nil
}

// Clean removes the dist directory entirely.
func Clean(distDir string) error {
	if err := validateDistDir(distDir, ""); err != nil {
		return err
	}
	if err := os.RemoveAll(distDir); err != nil {
		return fmt.Errorf("remove %s: %w", distDir, err)
	}
	return nil
}

// validateDistDir checks that distDir is safe to wipe.
func validateDistDir(distDir, srcDir string) error {
	clean := filepath.Clean(distDir)

	// Reject dangerous paths.
	if clean == "." || clean == ".." {
		return fmt.Errorf("dist directory %q is not a safe path", distDir)
	}

	// Must not be the source directory.
	if srcDir != "" {
		srcClean := filepath.Clean(srcDir)
		if clean == srcClean {
			return fmt.Errorf("dist directory %q must not be the same as source directory %q", distDir, srcDir)
		}
		// Must not be a parent of source.
		rel, err := filepath.Rel(clean, srcClean)
		if err == nil && !strings.HasPrefix(rel, "..") {
			return fmt.Errorf("dist directory %q must not be a parent of source directory %q", distDir, srcDir)
		}
	}

	// If the directory already exists, it must contain our sentinel
	// (or be empty). This prevents wiping unrelated directories.
	if info, err := os.Stat(distDir); err == nil && info.IsDir() {
		if _, err := os.Stat(filepath.Join(distDir, sentinel)); err != nil {
			// Check if the directory is empty.
			entries, readErr := os.ReadDir(distDir)
			if readErr != nil {
				return fmt.Errorf("cannot read dist directory %q: %w", distDir, readErr)
			}
			if len(entries) > 0 {
				return fmt.Errorf("dist directory %q exists but was not created by hamr gen static (missing %s sentinel)", distDir, sentinel)
			}
		}
	}

	return nil
}

// hashFile returns the first hashLen hex characters of the SHA-256 digest.
func hashFile(path string) (string, error) {
	f, err := os.Open(path)
	if err != nil {
		return "", err
	}
	defer f.Close() //nolint:errcheck

	h := sha256.New()
	if _, err := io.Copy(h, f); err != nil {
		return "", err
	}
	return hex.EncodeToString(h.Sum(nil))[:hashLen], nil
}

// fingerprintedName inserts the hash before the file extension.
// e.g. "output.css" + "a1b2c3d4e5f6" → "output.a1b2c3d4e5f6.css"
func fingerprintedName(name, hash string) string {
	ext := filepath.Ext(name)
	base := strings.TrimSuffix(name, ext)
	return base + "." + hash + ext
}

// copyFile copies src to dst, creating parent directories as needed.
func copyFile(src, dst string) error {
	in, err := os.Open(src)
	if err != nil {
		return err
	}
	defer in.Close() //nolint:errcheck

	info, err := in.Stat()
	if err != nil {
		return err
	}

	if err := os.MkdirAll(filepath.Dir(dst), 0o755); err != nil {
		return err
	}

	out, err := os.OpenFile(dst, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, info.Mode())
	if err != nil {
		return err
	}

	if _, err := io.Copy(out, in); err != nil {
		out.Close() //nolint:errcheck
		return err
	}
	return out.Close()
}

// IsFingerprinted reports whether the given URL path contains a fingerprint hash.
func IsFingerprinted(path string) bool {
	return fingerprintPattern.MatchString(path)
}
